window.API = window.API || {};
window.API.getHistory = function(){
  return [
     {
        "user":{
           "id":4103934,
           "username":"Powdered Toast Man シ"
        },
        "media":{
           "author":"Romare",
           "cid":"NekoiOaCV_M",
           "duration":312,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/NekoiOaCV_M/default.jpg",
           "title":"Motherless Child"
        },
        "score":{
           "positive":21,
           "negative":0,
           "grabs":0,
           "listeners":46
        }
     },
     {
        "user":{
           "id":13447599,
           "username":"Plastic Tree"
        },
        "media":{
           "author":"Gramatik",
           "cid":"_m2zGncgLjw",
           "duration":205,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/_m2zGncgLjw/default.jpg",
           "title":"Hit That Jive "
        },
        "score":{
           "grabs":0,
           "listeners":46,
           "negative":1,
           "positive":21,
           "skipped":0
        }
     },
     {
        "user":{
           "id":5019150,
           "username":"Surfing"
        },
        "media":{
           "author":"bdhd.",
           "cid":"271451736",
           "duration":145,
           "format":2,
           "id":"0",
           "image":"//i1.sndcdn.com/artworks-000169490827-wdwpbk-large.jpg",
           "title":"morning [in the tropics]"
        },
        "score":{
           "grabs":0,
           "listeners":44,
           "negative":0,
           "positive":21,
           "skipped":0
        }
     },
     {
        "user":{
           "id":3526348,
           "username":"owltea"
        },
        "media":{
           "author":"Avanti",
           "cid":"150746799",
           "duration":370,
           "format":2,
           "id":"0",
           "image":"//i1.sndcdn.com/artworks-000080173499-npep1j-large.jpg",
           "title":"Black Magic (Sare Havlicek Remix)"
        },
        "score":{
           "grabs":0,
           "listeners":45,
           "negative":0,
           "positive":22,
           "skipped":0
        }
     },
     {
        "user":{
           "id":5019150,
           "username":"Surfing"
        },
        "media":{
           "author":"driver",
           "cid":"245135591",
           "duration":133,
           "format":2,
           "id":"0",
           "image":"//i1.sndcdn.com/artworks-000145632540-00yt67-large.jpg",
           "title":"DRINKIN A 40 IN A DEATH BASKET"
        },
        "score":{
           "grabs":0,
           "listeners":46,
           "negative":0,
           "positive":21,
           "skipped":0
        }
     },
     {
        "user":{
           "id":20592480,
           "username":"Garnifa"
        },
        "media":{
           "author":"Maeckes",
           "cid":"sa2pH2oOKmQ",
           "duration":223,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/sa2pH2oOKmQ/default.jpg",
           "title":"Gettin‘ Jiggy With It"
        },
        "score":{
           "grabs":0,
           "listeners":50,
           "negative":0,
           "positive":13,
           "skipped":1
        }
     },
     {
        "user":{
           "id":4107352,
           "username":"CoLd_Friction"
        },
        "media":{
           "author":"Susumu Yokota",
           "cid":"FjtEZp61KTg",
           "duration":288,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/FjtEZp61KTg/default.jpg",
           "title":"Tobiume"
        },
        "score":{
           "grabs":0,
           "listeners":50,
           "negative":1,
           "positive":22,
           "skipped":0
        }
     },
     {
        "user":{
           "id":3583431,
           "username":"Daniel Zlobik"
        },
        "media":{
           "author":"Jalan Jalan",
           "cid":"52GAt_fPX1k",
           "duration":388,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/52GAt_fPX1k/default.jpg",
           "title":"Lotus (Soundtrack of Dragonhunters)"
        },
        "score":{
           "grabs":0,
           "listeners":49,
           "negative":2,
           "positive":23,
           "skipped":0
        }
     },
     {
        "user":{
           "id":7384094,
           "username":"kiwi_da_kiz"
        },
        "media":{
           "author":"SHREK",
           "cid":"IQbQtQu_uOI",
           "duration":58,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/IQbQtQu_uOI/default.jpg",
           "title":"GR8 BEET5 BYE DRE"
        },
        "score":{
           "grabs":0,
           "listeners":51,
           "negative":0,
           "positive":3,
           "skipped":1
        }
     },
     {
        "user":{
           "id":3557906,
           "username":"DjArum19  シ"
        },
        "media":{
           "author":"Eko_Fisk",
           "cid":"EYAv6pAbk4U",
           "duration":283,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/EYAv6pAbk4U/default.jpg",
           "title":"Solstice II"
        },
        "score":{
           "grabs":0,
           "listeners":51,
           "negative":2,
           "positive":23,
           "skipped":0
        }
     },
     {
        "user":{
           "id":4511710,
           "username":"DJsann"
        },
        "media":{
           "author":"KILLEREYSA",
           "cid":"KJ2FDV4w9Nk",
           "duration":173,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/KJ2FDV4w9Nk/default.jpg",
           "title":"Best Relaxing Music (clear your mind)"
        },
        "score":{
           "grabs":0,
           "listeners":54,
           "negative":1,
           "positive":23,
           "skipped":0
        }
     },
     {
        "user":{
           "id":13447599,
           "username":"Plastic Tree"
        },
        "media":{
           "author":"Mud Flow",
           "cid":"CU_7KvZW-34",
           "duration":155,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/CU_7KvZW-34/default.jpg",
           "title":"The Sense Of Me"
        },
        "score":{
           "grabs":3,
           "listeners":54,
           "negative":2,
           "positive":23,
           "skipped":0
        }
     },
     {
        "user":{
           "id":5019150,
           "username":"Surfing"
        },
        "media":{
           "author":"ROOK1E",
           "cid":"255077216",
           "duration":168,
           "format":2,
           "id":"0",
           "image":"//i1.sndcdn.com/artworks-000168758944-ew6ldf-large.jpg",
           "title":"[don't know why.]"
        },
        "score":{
           "grabs":0,
           "listeners":55,
           "negative":4,
           "positive":21,
           "skipped":0
        }
     },
     {
        "user":{
           "id":16994660,
           "username":"Reclaimed"
        },
        "media":{
           "author":"CMA",
           "cid":"I0LNAV_Rqvw",
           "duration":287,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/I0LNAV_Rqvw/default.jpg",
           "title":"The Small Losses (Full Version)"
        },
        "score":{
           "grabs":1,
           "listeners":59,
           "negative":0,
           "positive":28,
           "skipped":0
        }
     },
     {
        "user":{
           "id":3583431,
           "username":"Daniel Zlobik"
        },
        "media":{
           "author":"Tom Day",
           "cid":"BVomQtrtMTM",
           "duration":397,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/BVomQtrtMTM/default.jpg",
           "title":"Who We Want To Be"
        },
        "score":{
           "grabs":0,
           "listeners":59,
           "negative":0,
           "positive":24,
           "skipped":0
        }
     },
     {
        "user":{
           "id":3996856,
           "username":"Kode Of Bliss"
        },
        "media":{
           "author":"Kode of Bliss",
           "cid":"B_KJOCR9G7Y",
           "duration":279,
           "format":1,
           "id":"0",
           "image":"//i1.ytimg.com/vi/B_KJOCR9G7Y/default.jpg",
           "title":"Bright Suns"
        },
        "score":{
           "grabs":1,
           "listeners":56,
           "negative":0,
           "positive":26,
           "skipped":0
        }
     },
     {
        "user":{
           "id":3929282,
           "username":"Molly"
        },
        "media":{
           "author":"Jazzinuf",
           "cid":"NMAcxqk5M7w",
           "duration":195,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/NMAcxqk5M7w/default.jpg",
           "title":"Coffee And Cigarettes"
        },
        "score":{
           "grabs":0,
           "listeners":57,
           "negative":4,
           "positive":24,
           "skipped":0
        }
     },
     {
        "user":{
           "id":16145806,
           "username":"Daniel Onofre"
        },
        "media":{
           "author":"The Eden Project",
           "cid":"IKaNodcBiLA",
           "duration":260,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/IKaNodcBiLA/default.jpg",
           "title":"Drowning"
        },
        "score":{
           "grabs":1,
           "listeners":55,
           "negative":3,
           "positive":25,
           "skipped":1
        }
     },
     {
        "user":{
           "id":6956271,
           "username":"sxcwog"
        },
        "media":{
           "author":"Knight Ali",
           "cid":"289314186",
           "duration":216,
           "format":2,
           "id":"0",
           "image":"//i1.sndcdn.com/artworks-000190012710-76c5xm-large.jpg",
           "title":"Unregistered Feelings"
        },
        "score":{
           "grabs":0,
           "listeners":56,
           "negative":1,
           "positive":26,
           "skipped":0
        }
     },
     {
        "user":{
           "id":6665539,
           "username":"George 7.36"
        },
        "media":{
           "author":"GEORGE MICHAEL",
           "cid":"MbZWnRvKGg8",
           "duration":264,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/MbZWnRvKGg8/default.jpg",
           "title":"Last Christmas"
        },
        "score":{
           "grabs":2,
           "listeners":57,
           "negative":3,
           "positive":24,
           "skipped":0
        }
     },
     {
        "user":{
           "id":3557906,
           "username":"DjArum19  シ"
        },
        "media":{
           "author":"Erot",
           "cid":"9v4v9zK9WRo",
           "duration":368,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/9v4v9zK9WRo/default.jpg",
           "title":"Zodiacal Light (Original Mix)"
        },
        "score":{
           "grabs":1,
           "listeners":56,
           "negative":0,
           "positive":25,
           "skipped":0
        }
     },
     {
        "user":{
           "id":4815968,
           "username":"Smartenne"
        },
        "media":{
           "author":"Metal Gear Solid V",
           "cid":"RrkzIN2eP0U",
           "duration":303,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/RrkzIN2eP0U/default.jpg",
           "title":"Phantom Pain ''Nuclear'' Lyrics [HD]"
        },
        "score":{
           "grabs":0,
           "listeners":56,
           "negative":0,
           "positive":20,
           "skipped":1
        }
     },
     {
        "user":{
           "id":3963175,
           "username":"Looneytoonie シ"
        },
        "media":{
           "author":"Hot Chip",
           "cid":"bZtgsUHdwP4",
           "duration":503,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/bZtgsUHdwP4/default.jpg",
           "title":"Flutes (Sasha remix)"
        },
        "score":{
           "grabs":0,
           "listeners":56,
           "negative":0,
           "positive":27,
           "skipped":0
        }
     },
     {
        "user":{
           "id":19192459,
           "username":"Lachlan2525"
        },
        "media":{
           "author":"Blackbear",
           "cid":"gxE4ngu78Ro",
           "duration":250,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/gxE4ngu78Ro/default.jpg",
           "title":"Idfc (Tarro Remix)"
        },
        "score":{
           "grabs":0,
           "listeners":59,
           "negative":2,
           "positive":21,
           "skipped":1
        }
     },
     {
        "user":{
           "id":5019150,
           "username":"Surfing"
        },
        "media":{
           "author":"sumthin gunny",
           "cid":"152247959",
           "duration":133,
           "format":2,
           "id":"0",
           "image":"//i1.sndcdn.com/artworks-000081097987-j0klhb-large.jpg?30a2558",
           "title":"solitary saturday"
        },
        "score":{
           "grabs":0,
           "listeners":59,
           "negative":1,
           "positive":26,
           "skipped":0
        }
     },
     {
        "user":{
           "id":13447599,
           "username":"Plastic Tree"
        },
        "media":{
           "author":"Yeiv",
           "cid":"5U2zikUS7D4",
           "duration":243,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/5U2zikUS7D4/default.jpg",
           "title":"Let It Marinate (Instrumental)"
        },
        "score":{
           "grabs":2,
           "listeners":59,
           "negative":1,
           "positive":24,
           "skipped":0
        }
     },
     {
        "user":{
           "id":3798150,
           "username":"Krіs"
        },
        "media":{
           "author":"Mark Knight",
           "cid":"lVgerFg0FWU",
           "duration":223,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/lVgerFg0FWU/default.jpg",
           "title":"Your Love"
        },
        "score":{
           "grabs":0,
           "listeners":59,
           "negative":3,
           "positive":23,
           "skipped":0
        }
     },
     {
        "user":{
           "id":4328984,
           "username":"DJWEX"
        },
        "media":{
           "author":"Ruby My Dear",
           "cid":"ygkPhYCMrxQ",
           "duration":406,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/ygkPhYCMrxQ/default.jpg",
           "title":"Karoshi"
        },
        "score":{
           "grabs":0,
           "listeners":64,
           "negative":5,
           "positive":24,
           "skipped":1
        }
     },
     {
        "user":{
           "id":4090653,
           "username":"MC Scruffalicious"
        },
        "media":{
           "author":"soundvoyage",
           "cid":"03hC_Ml8aAM",
           "duration":309,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/03hC_Ml8aAM/default.jpg",
           "title":"TV On The Radio Wolf Like Me"
        },
        "score":{
           "grabs":0,
           "listeners":66,
           "negative":1,
           "positive":24,
           "skipped":1
        }
     },
     {
        "user":{
           "id":3583431,
           "username":"Daniel Zlobik"
        },
        "media":{
           "author":"Tom Day",
           "cid":"QhDv9Gwj5wI",
           "duration":332,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/QhDv9Gwj5wI/default.jpg",
           "title":"Going Home"
        },
        "score":{
           "grabs":2,
           "listeners":66,
           "negative":0,
           "positive":31,
           "skipped":0
        }
     },
     {
        "user":{
           "id":16145806,
           "username":"Daniel Onofre"
        },
        "media":{
           "author":"EDEN",
           "cid":"0pVABElms84",
           "duration":241,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/0pVABElms84/default.jpg",
           "title":"End Credits"
        },
        "score":{
           "grabs":0,
           "listeners":65,
           "negative":4,
           "positive":30,
           "skipped":0
        }
     },
     {
        "user":{
           "id":3572341,
           "username":"clixxi"
        },
        "media":{
           "author":"Black Sun Empire & Audio",
           "cid":"VH5lhjrck40",
           "duration":323,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/VH5lhjrck40/default.jpg",
           "title":"Drizzle"
        },
        "score":{
           "grabs":0,
           "listeners":65,
           "negative":1,
           "positive":26,
           "skipped":1
        }
     },
     {
        "user":{
           "id":11924344,
           "username":"A-7b91"
        },
        "media":{
           "author":"cband1t",
           "cid":"qHFxncb1gRY",
           "duration":485,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/qHFxncb1gRY/default.jpg",
           "title":"Stairway to Heaven Led Zeppelin Lyrics"
        },
        "score":{
           "grabs":0,
           "listeners":66,
           "negative":0,
           "positive":18,
           "skipped":1
        }
     },
     {
        "user":{
           "id":3557906,
           "username":"DjArum19  シ"
        },
        "media":{
           "author":"Virtual Boy",
           "cid":"C3DPxfs2v8o",
           "duration":451,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/C3DPxfs2v8o/default.jpg",
           "title":"Mass"
        },
        "score":{
           "grabs":1,
           "listeners":66,
           "negative":0,
           "positive":33,
           "skipped":0
        }
     },
     {
        "user":{
           "id":3833117,
           "username":"*FRESHLY CHILL*"
        },
        "media":{
           "author":"Vijay &amp; Sofia Zlatko",
           "cid":"I0SIR__oG-w",
           "duration":278,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/I0SIR__oG-w/default.jpg",
           "title":"Labour (Feat. GuitK)"
        },
        "score":{
           "grabs":1,
           "listeners":68,
           "negative":0,
           "positive":32,
           "skipped":0
        }
     },
     {
        "user":{
           "id":6405076,
           "username":"MajkeldziadulotroN"
        },
        "media":{
           "author":"Ruby My Dear",
           "cid":"kXinBvgp9Vg",
           "duration":438,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/kXinBvgp9Vg/default.jpg",
           "title":"Shee"
        },
        "score":{
           "grabs":1,
           "listeners":69,
           "negative":0,
           "positive":37,
           "skipped":0
        }
     },
     {
        "user":{
           "id":7896987,
           "username":"Dj_Sokry"
        },
        "media":{
           "author":"Ben Phipps",
           "cid":"a8kN8R5narM",
           "duration":197,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/a8kN8R5narM/default.jpg",
           "title":"Sleep Alone (feat. Ashe)‏"
        },
        "score":{
           "grabs":1,
           "listeners":69,
           "negative":0,
           "positive":32,
           "skipped":0
        }
     },
     {
        "user":{
           "id":3009768,
           "username":"GorillaCZ"
        },
        "media":{
           "author":"vealon",
           "cid":"cxoc9QdPYMU",
           "duration":360,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/cxoc9QdPYMU/default.jpg",
           "title":"Whisper (ft. Hanna Alderblad & Hanna Rubensson)"
        },
        "score":{
           "grabs":1,
           "listeners":70,
           "negative":4,
           "positive":31,
           "skipped":1
        }
     },
     {
        "user":{
           "id":4106809,
           "username":"Moistcarrot"
        },
        "media":{
           "author":"Sheep Raider OST",
           "cid":"WiMky9D1bog",
           "duration":179,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/WiMky9D1bog/default.jpg",
           "title":"Track 2 (CD Quality)"
        },
        "score":{
           "grabs":0,
           "listeners":71,
           "negative":3,
           "positive":23,
           "skipped":1
        }
     },
     {
        "user":{
           "id":3970251,
           "username":"VoltzHead2099"
        },
        "media":{
           "author":"Jaswan",
           "cid":"LDC2iecl6ZY",
           "duration":114,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/LDC2iecl6ZY/default.jpg",
           "title":"shes my lover"
        },
        "score":{
           "grabs":0,
           "listeners":71,
           "negative":0,
           "positive":31,
           "skipped":0
        }
     },
     {
        "user":{
           "id":4136963,
           "username":"Healer"
        },
        "media":{
           "author":"Sonis R.",
           "cid":"RJpBaQYLrUY",
           "duration":473,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/RJpBaQYLrUY/default.jpg",
           "title":"The Flight"
        },
        "score":{
           "grabs":0,
           "listeners":72,
           "negative":0,
           "positive":34,
           "skipped":0
        }
     },
     {
        "user":{
           "id":3669014,
           "username":"errbody"
        },
        "media":{
           "author":"Human Action Network",
           "cid":"aI5WDVV6ZCk",
           "duration":262,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/aI5WDVV6ZCk/default.jpg",
           "title":"Cooper's Wine"
        },
        "score":{
           "grabs":0,
           "listeners":76,
           "negative":0,
           "positive":34,
           "skipped":0
        }
     },
     {
        "user":{
           "id":5019150,
           "username":"Surfing"
        },
        "media":{
           "author":"In love with a ghost",
           "cid":"237415975",
           "duration":133,
           "format":2,
           "id":"0",
           "image":"//i1.sndcdn.com/artworks-000139459754-k83few-large.jpg",
           "title":"sorry for not answering the phone, i'm too busy trying to fly away"
        },
        "score":{
           "grabs":0,
           "listeners":78,
           "negative":0,
           "positive":32,
           "skipped":0
        }
     },
     {
        "user":{
           "id":13447599,
           "username":"Plastic Tree"
        },
        "media":{
           "author":"GooMar",
           "cid":"UQpH3dbZjkE",
           "duration":139,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/UQpH3dbZjkE/default.jpg",
           "title":"Unquiet Serenade"
        },
        "score":{
           "grabs":1,
           "listeners":76,
           "negative":2,
           "positive":36,
           "skipped":0
        }
     },
     {
        "user":{
           "id":6608098,
           "username":"Sexy Cherry"
        },
        "media":{
           "author":"Bronze Whale",
           "cid":"zj9ON8OVZbg",
           "duration":319,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/zj9ON8OVZbg/default.jpg",
           "title":"Say It (BAILE Remix)"
        },
        "score":{
           "grabs":0,
           "listeners":76,
           "negative":1,
           "positive":36,
           "skipped":0
        }
     },
     {
        "user":{
           "id":3583431,
           "username":"Daniel Zlobik"
        },
        "media":{
           "author":"Sigma",
           "cid":"eYCxGBjrI4U",
           "duration":272,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/eYCxGBjrI4U/default.jpg",
           "title":"Nobody To Love (Sigma's Future Jungle Mix)"
        },
        "score":{
           "grabs":1,
           "listeners":68,
           "negative":0,
           "positive":37,
           "skipped":0
        }
     },
     {
        "user":{
           "id":7896987,
           "username":"Dj_Sokry"
        },
        "media":{
           "author":"Peking Duk Ft SAFIA",
           "cid":"EesW1dQy480",
           "duration":241,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/EesW1dQy480/default.jpg",
           "title":"Take Me Over (Benson Remix)"
        },
        "score":{
           "grabs":0,
           "listeners":67,
           "negative":0,
           "positive":35,
           "skipped":0
        }
     },
     {
        "user":{
           "id":6691756,
           "username":"FishTøast"
        },
        "media":{
           "author":"Logistics",
           "cid":"89jiovMRL0U",
           "duration":316,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/89jiovMRL0U/default.jpg",
           "title":"Okinawa"
        },
        "score":{
           "grabs":1,
           "listeners":67,
           "negative":0,
           "positive":35,
           "skipped":0
        }
     },
     {
        "user":{
           "id":16058962,
           "username":"newacc04nt"
        },
        "media":{
           "author":"Dandy in love",
           "cid":"jjaELKsl2eU",
           "duration":146,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/jjaELKsl2eU/default.jpg",
           "title":"Space Dandy OST"
        },
        "score":{
           "grabs":0,
           "listeners":65,
           "negative":0,
           "positive":33,
           "skipped":0
        }
     },
     {
        "user":{
           "id":11924344,
           "username":"A-7b91"
        },
        "media":{
           "author":"The Eden Project",
           "cid":"ZdbpYU_OIBE",
           "duration":243,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/ZdbpYU_OIBE/default.jpg",
           "title":"Jupiter"
        },
        "score":{
           "grabs":2,
           "listeners":66,
           "negative":4,
           "positive":31,
           "skipped":0
        }
     },
     {
        "user":{
           "id":3833117,
           "username":"*FRESHLY CHILL*"
        },
        "media":{
           "author":"NANKOO",
           "cid":"yHWYU8Y8my0",
           "duration":505,
           "format":1,
           "id":"0",
           "image":"//i.ytimg.com/vi/yHWYU8Y8my0/default.jpg",
           "title":"NDGO (T. Finland Remix)"
        },
        "score":{
           "grabs":1,
           "listeners":68,
           "negative":0,
           "positive":34,
           "skipped":0
        }
     }
  ]
};
